"""Exploration loop integration tests (Section 2.2).

Tests the flow: Scenario activation -> Lab hypothesis -> Pattern discovery ->
Hypothesis ranking.

Validates:
1. Lab generates hypotheses from released data
2. Each hypothesis has falsification_tests
3. constraint_violation_report labeled "预筛结果，非权威"
4. Lab isolation verified
"""

from __future__ import annotations

import pytest
from httpx import AsyncClient

pytestmark = pytest.mark.integration


async def test_lab_generates_hypotheses(api_client: AsyncClient) -> None:
    """Lab generates hypotheses from released constraint data."""
    constraints = [
        {
            "constraint_id": "cc-temp-limit",
            "scenario_criticality": "safety_critical",
            "validation": {
                "type": "range",
                "config": {"variable": "temperature", "min": 0, "max": 100},
            },
        }
    ]
    data = {"state_variables": {"temperature": 65.3}}

    response = await api_client.post(
        "/api/v1/lab/explore/hypothesis",
        json={"data": data, "constraints": constraints},
    )
    assert response.status_code == 200
    result = response.json()
    assert "hypotheses" in result
    assert result["count"] >= 0


async def test_hypotheses_have_falsification_tests(
    api_client: AsyncClient,
) -> None:
    """Each hypothesis generated by Lab must have falsification_tests."""
    constraints = [
        {
            "constraint_id": "cc-temp-limit",
            "scenario_criticality": "operational",
            "validation": {
                "type": "range",
                "config": {"variable": "temperature", "min": 10, "max": 90},
            },
        }
    ]
    data = {"state_variables": {"temperature": 50.0}}

    response = await api_client.post(
        "/api/v1/lab/explore/hypothesis",
        json={"data": data, "constraints": constraints},
    )
    assert response.status_code == 200
    result = response.json()
    for hyp in result["hypotheses"]:
        assert "falsification_tests" in hyp
        assert isinstance(hyp["falsification_tests"], list)


async def test_constraint_violation_report_prescreen_label(
    api_client: AsyncClient,
) -> None:
    """CandidateModelPackage constraint_violation_report always says "预筛结果，非权威"."""
    candidates = [
        {
            "model_id": "model-001",
            "architecture_description": "Test model",
            "training_data_lineage": "lineage-001",
        }
    ]

    response = await api_client.post(
        "/api/v1/lab/submit",
        json={"candidates": candidates},
    )
    assert response.status_code == 200
    result = response.json()
    # The response should have hidden_set_info_exposed = False
    assert result["hidden_set_info_exposed"] is False
    # Aggregate summary should be non-empty
    assert result["aggregate_summary"]


async def test_lab_counterexample_search(api_client: AsyncClient) -> None:
    """Lab counterexample search finds boundary violations."""
    constraints = [
        {
            "constraint_id": "cc-temp-limit",
            "scenario_criticality": "safety_critical",
            "validation": {
                "type": "range",
                "config": {"variable": "temperature", "min": 0, "max": 100},
            },
        }
    ]
    data = {"state_variables": {"temperature": 65.3}}

    response = await api_client.post(
        "/api/v1/lab/explore/counterexample",
        json={"data": data, "constraints": constraints},
    )
    assert response.status_code == 200
    result = response.json()
    assert "counterexamples" in result
    # AlgorithmicStrategy should find at least 2 boundary violations (above max, below min)
    assert result["count"] >= 2


async def test_lab_data_release_no_hidden_exposure(
    api_client: AsyncClient,
) -> None:
    """Data release endpoint never exposes hidden validation sets."""
    response = await api_client.get("/api/v1/lab/data-release/dp-test-001")
    assert response.status_code == 200
    result = response.json()
    assert result["hidden_exposure"] is False
    # The data itself should not contain hidden references
    data_str = str(result).lower()
    hidden_keywords = [
        "hidden_challenge_set",
        "hidden_validation_set",
        "audit_benchmark_reference",
        "production_acceptance_reference",
    ]
    for kw in hidden_keywords:
        assert kw not in data_str, f"Data release contains hidden reference: {kw}"


async def test_lab_correlation_analysis(api_client: AsyncClient) -> None:
    """Lab failure correlation analysis runs successfully."""
    failure_logs = [
        {"event_id": "evt-001", "constraint_id": "cc-temp", "status": "failed"},
        {"event_id": "evt-002", "constraint_id": "cc-pressure", "status": "failed"},
    ]

    response = await api_client.post(
        "/api/v1/lab/explore/correlation",
        json={"failure_logs": failure_logs},
    )
    assert response.status_code == 200
    result = response.json()
    assert "findings" in result


async def test_lab_strategies_list(api_client: AsyncClient) -> None:
    """Lab can list available exploration strategies."""
    response = await api_client.get("/api/v1/lab/strategies")
    assert response.status_code == 200
    result = response.json()
    assert "strategies" in result
    assert len(result["strategies"]) >= 1
    strategy = result["strategies"][0]
    assert "name" in strategy
    assert "constraint_awareness" in strategy
