"""Lab-specific types for the isolated exploration engine.

Defines data models for exploration budgets, findings, hypotheses,
counterexamples, counterfactual scenarios, correlation analysis,
exploration results, candidate model packages, and submission payloads.

Key invariants:
- CandidateModelPackage.constraint_violation_report ALWAYS contains the label
  "预筛结果，非权威" (prescreen result, not authoritative).
- LabSubmissionResponse.hidden_set_info_exposed is ALWAYS False.
- LabSubmission.is_prescreen is ALWAYS True.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

# ── Budget & constraints ───────────────────────────────────────────


class ExplorationBudget(BaseModel):
    """Resource budget for a single exploration run."""

    max_iterations: int = 1000
    max_time_seconds: float = 60.0
    max_memory_mb: float = 512.0
    max_cpu_percent: float = 80.0


# ── Findings ───────────────────────────────────────────────────────


class Finding(BaseModel):
    """A single finding discovered during exploration."""

    finding_id: str = ""
    type: str = ""  # counterexample, pattern, anomaly
    description: str = ""
    confidence: float = 0.0
    data: dict = Field(default_factory=dict)


class Hypothesis(BaseModel):
    """A testable hypothesis generated by the Lab."""

    hypothesis_id: str = ""
    statement: str = ""
    falsification_tests: list[dict] = Field(default_factory=list)
    supporting_evidence: list[str] = Field(default_factory=list)
    confidence: float = 0.0


class Counterexample(BaseModel):
    """A concrete input state that violates a constraint."""

    counterexample_id: str = ""
    model_id: str = ""
    state_at_failure: dict = Field(default_factory=dict)
    constraint_violated: str = ""
    severity: str = "medium"


class CounterfactualScenario(BaseModel):
    """An alternative state scenario for divergence analysis."""

    scenario_id: str = ""
    base_state: dict = Field(default_factory=dict)
    modified_state: dict = Field(default_factory=dict)
    divergence_score: float = 0.0
    models_disagree: bool = False


class CorrelationFinding(BaseModel):
    """A correlation discovered between failure events."""

    finding_id: str = ""
    event_sequence: list[dict] = Field(default_factory=list)
    correlation_strength: float = 0.0
    statistical_significance: float = 0.0


# ── Aggregated results ─────────────────────────────────────────────


class ExplorationResult(BaseModel):
    """Aggregated output from a single exploration strategy run."""

    findings: list[Finding] = Field(default_factory=list)
    hypotheses: list[Hypothesis] = Field(default_factory=list)
    counterexamples: list[Counterexample] = Field(default_factory=list)
    confidence_scores: dict[str, float] = Field(default_factory=dict)
    strategy_manifest: dict = Field(default_factory=dict)


# ── Submission ──────────────────────────────────────────────────────


class CandidateModelPackage(BaseModel):
    """A candidate model package assembled by the Lab for submission.

    Key invariant: ``constraint_violation_report`` always carries the
    label "预筛结果，非权威" to signal that this is a Lab prescreen,
    not an authoritative Core determination.
    """

    model_id: str = ""
    architecture_description: str = ""
    training_data_lineage: str = ""
    constraint_violation_report: str = "预筛结果，非权威"
    reproducibility_recipe: dict = Field(default_factory=dict)


class LabSubmission(BaseModel):
    """A batch of candidate packages submitted from Lab to Core."""

    submission_id: str = ""
    items: list[CandidateModelPackage] = Field(default_factory=list)
    strategy_manifest: dict = Field(default_factory=dict)
    is_prescreen: bool = True


class LabSubmissionResponse(BaseModel):
    """Response returned to Lab after submission processing.

    Key invariant: ``hidden_set_info_exposed`` is always False — the
    Lab must never learn whether rejection was due to a hidden
    validation set.
    """

    submission_id: str = ""
    item_results: list[dict] = Field(default_factory=list)
    aggregate_summary: str = ""
    hidden_set_info_exposed: bool = False


class StrategyManifest(BaseModel):
    """Metadata describing an exploration strategy's identity and reproducibility."""

    name: str = ""
    version: str = "0.1.0"
    reproducibility: dict = Field(default_factory=dict)
    constraint_awareness_level: str = "algorithmic"
